/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as auth_rootRouteImport } from './routes/(auth)/__root'
import { Route as TableOrderRouteImport } from './routes/table-order'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as OrderRouteImport } from './routes/order'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const auth_rootRoute = auth_rootRouteImport.update({
  id: '/(auth)/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const TableOrderRoute = TableOrderRouteImport.update({
  id: '/table-order',
  path: '/table-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/employee': typeof EmployeeRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/order': typeof OrderRoute
  '/sales': typeof SalesRoute
  '/table-order': typeof TableOrderRoute
  '/': typeof auth_rootRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesByTo {
  '/employee': typeof EmployeeRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/order': typeof OrderRoute
  '/sales': typeof SalesRoute
  '/table-order': typeof TableOrderRoute
  '/': typeof auth_rootRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/employee': typeof EmployeeRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/order': typeof OrderRoute
  '/sales': typeof SalesRoute
  '/table-order': typeof TableOrderRoute
  '/(auth)/__root': typeof auth_rootRoute
  '/(auth)/login': typeof authLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/employee'
    | '/expenses'
    | '/inventory'
    | '/order'
    | '/sales'
    | '/table-order'
    | '/'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/employee'
    | '/expenses'
    | '/inventory'
    | '/order'
    | '/sales'
    | '/table-order'
    | '/'
    | '/login'
  id:
    | '__root__'
    | '/employee'
    | '/expenses'
    | '/inventory'
    | '/order'
    | '/sales'
    | '/table-order'
    | '/(auth)/__root'
    | '/(auth)/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EmployeeRoute: typeof EmployeeRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  OrderRoute: typeof OrderRoute
  SalesRoute: typeof SalesRoute
  TableOrderRoute: typeof TableOrderRoute
  auth_rootRoute: typeof auth_rootRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/__root': {
      id: '/(auth)/__root'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof auth_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-order': {
      id: '/table-order'
      path: '/table-order'
      fullPath: '/table-order'
      preLoaderRoute: typeof TableOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EmployeeRoute: EmployeeRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  OrderRoute: OrderRoute,
  SalesRoute: SalesRoute,
  TableOrderRoute: TableOrderRoute,
  auth_rootRoute: auth_rootRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
